### ISSUE TITLE
Replace debug mode with release

### ISSUE THREAD

**Issue by mrMiiao** [idewave/idewave-cli#31]
Replace `cargo run` in README with `cargo run -r`

**Comment by sergio-ivanuzzo** [comment]
> Replace `cargo run` in README with `cargo run -r`

Could you clarify, does `cargo run` by default related to `debug` ?

**Comment by mrMiiao** [comment]
Yes, the standard profile is debug. `-r` switches profile to release. You can customize build profiles in `Cargo.toml` via `[profile]`

**Comment by sergio-ivanuzzo** [comment]
> Yes, the standard profile is debug. `-r` switches profile to release. You can customize build profiles in `Cargo.toml` via `[profile]`

I got it, will do. Thank you for explanation !
